name: Coverity Analysis Action
description: Performs the Coverity Analysis and Sends the report to Coverity Server
author: "lokeshkamalay"
inputs:
  stream:
    description: "Application Name in Coverity"
    required: true
# runs:
#   using: "composite"
#   steps:
#     - name: printing the var
#       run: |
#         printenv
#         echo "This is the token ${{ github.token }}"
#         echo "========"
#         printenv | grep -i github
#       shell: bash
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    github_token: ${{ github.token }}