name: Testing
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: verifying
        uses: ./
        with:
          stream: DevOps-Example #The stream name as per Coverity Project
